site_name: MSBA 504
site_url: https://dcyoung23.github.io/msba504/
repo_url: https://github.com/dcyoung23/msba504
repo_name: MSBA 504
nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Assignments: assignments.md
  - Notes:
    - Week 1 - Intro / ER Models: notes/week_1.md
    - Week 2 - Relational Databases: notes/week_2.md
    - Week 3 - Create Database and ERD: notes/week_3.md
    - Week 4 - SQL Basics: notes/week_4.md
    - Week 5 - Intermediate SQL 1: notes/week_5.md
  - Resources:
    - Demos:
      - Create Conceptual ERD: demos/01_create_conceptual_erd.md
      - Implement Conceptual ERD: demos/02_implement_erd.md
      - Create Database and ERD: demos/03_create_database_erd.md
      - CRUD Operations: demos/04_crud_operations.md
      - Aggregating Data and JOINs: demos/05_aggregating_data_joins
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      tip: fontawesome/solid/lightbulb
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/dcyoung23
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dcyoung23/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Professor-Young
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/
      name: CC BY-NC-SA 4.0
  fontawesome:
    version: 6.0.0
  copyright: >
    Unless otherwise noted, the materials on this website and repository are freely available under the
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  version:
    provider: mike

extra_css:
  - css/extra.css

watch:
  - src

plugins:
  - search
  - macros:
      module_name: src/main
  - open-in-new-tab
  - mkdocs-jupyter:
      execute: false
